<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>Regia.Output</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <!-- Solo binari x64 di VLC -->
    <VlcWindowsX86IncludeFiles>false</VlcWindowsX86IncludeFiles>
    <VlcWindowsX64IncludeFiles>true</VlcWindowsX64IncludeFiles>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Regia.Core\Regia.Core.csproj" />
    <PackageReference Include="LibVLCSharp" />
    <PackageReference Include="NAudio.Wasapi" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" />
    <PackageReference Include="Microsoft.Windows.CsWin32" PrivateAssets="all" />
    <PackageReference Include="Serilog" />
  </ItemGroup>
</Project>
